version: 2

jobs:
  ansible_review:
    docker:
      - image: cimg/python:3.7.11
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: pipenv install
      - run: pipenv run ansible-review -q *playbook.yml
      - run: pipenv run ansible-lint *playbook.yml

workflows:
  version: 2
  lint_playbooks:
    jobs:
      - ansible_review
